title: fmt.Println("Hi, This is Suramrit!")
author: suramrit
theme: minima
email: suramrit@buffalo.edu
description: > # this means to ignore newlines until "baseurl:"
  suramrit singh resume 

# social links
twitter_username: suramrit # DO NOT include the @ character, or else the build will fail!
github_username:  suramrit # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
